apiVersion: v1
kind: Secret
metadata:
  name: jobber-backend-secret
  namespace: production
type: Opaque
data:
  # echo -n <secret> | base64
  secret-key-one: MDMyYzVjM2NmYzM3OTM4YWU2ZGQ0M2QzYTNlYzc4MzQ=
  secret-key-two: ZDY2ZTM3NzAxOGMwYmMwYjU3NzJiYmM5YjEzMWU2ZDk=
  gateway-jwt-token: MTI4MjcyMmI5NDJlMDhjOGE2Y2IwMzNhYTZjZTg1MGU=
  jwt-token: OGRiOGY4NTk5MWJiMjhmNDVhYzAxMDdmMmExYjM0OWM=
  jobber-redis-host: cmVkaXM6Ly86dGhpc2lzbXlvd25wYXNzd29yZDEyM0BAam9iYmVyLXJlZGlzLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OQ==
  sender-email: ZmVsaWNpdGEud2l6YTk5QGV0aGVyZWFsLmVtYWls
  sender-email-password: V1hlZnBhc21SN2p6ZDNzeWJC
  jobber-mysql-db: bXlzcWw6Ly9qb2JiZXI6YXBpQGpvYmJlci1teXNxbC5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjMzMDYvam9iYmVyX2F1dGg=
  jobber-postgres-host: am9iYmVyLXBvc3RncmVzLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw=
  jobber-postgres-user: am9iYmVy
  jobber-postgres-password: YXBp
  cloud-name: ZHlhbXI5eW0z
  cloud-api-key: Mzg1MjY5MTkzOTgyMTQ3
  cloud-api-secret: LWg5aFU0M1FNeTY4QWNJYU15UDBVTEtiaWJJ
  mongo-database-url: bW9uZ29kYjovL2pvYmJlci1tb25nby5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L2pvYmJlcg==
  stripe-api-key: c2tfdGVzdF81MU9BWHM2RFRnbHZNZUpQcmxYMUxwOU13N2FYd2xCYkZKT0xRZGxrRnY1bVJLUGtRZEZyeHZZTjY4eFo1NHdCcjZWYlA0NGtoU001VXBQdGZhaXhsTWdjVzAwQ0laRXBtbjU=
  stripe-client-key: c2tfdGVzdF81MU9BWHM2RFRnbHZNZUpQcmxYMUxwOU13N2FYd2xCYkZKT0xRZGxrRnY1bVJLUGtRZEZyeHZZTjY4eFo1NHdCcjZWYlA0NGtoU001VXBQdGZhaXhsTWdjVzAwQ0laRXBtbjU=
  jobber-rabbitmq-user: am9iYmVy
  jobber-rabbitmq-password: am9iYmVycGFzcw==
  jobber-rabbitmq-endpoint: YW1xcDovL2pvYmJlcjpqb2JiZXJwYXNzQGpvYmJlci1xdWV1ZS5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=
  jobber-elasticsearch-url: aHR0cDovL2VsYXN0aWM6YWRtaW4xMjM0QGpvYmJlci1lbGFzdGljLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6OTIwMA==
  jobber-elastic-apm-server-url: aHR0cDovL2pvYmJlci1hcG0ucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDo4MjAw
  jobber-elastic-apm-secret-token: dGhpc2lzbXlzZWNyZXR0b2tlbg==
  jobber-elasticsearch-host: am9iYmVyLWVsYXN0aWMucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbA==
  jobber-elasticsearch-username: ZWxhc3RpYw==
  jobber-elasticsearch-password: YWRtaW4xMjM0
