apiVersion: v1
kind: Service
metadata:
  name: jobber-postgres
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: jobber-postgres
  ports:
  - name: jobber-postgres
    port: 5432
    targetPort: 5432
