apiVersion: v1
kind: Secret
metadata:
  name: jobber-backend-secret
  namespace: production
type: Opaque
data:
  # echo -n <secret> | base64
  secret-key-one: MDMyYzVjM2NmYzM3OTM4YWU2ZGQ0M2QzYTNlYzc4MzQ=
  secret-key-two: ZDY2ZTM3NzAxOGMwYmMwYjU3NzJiYmM5YjEzMWU2ZDk=
  gateway-jwt-token: MTI4MjcyMmI5NDJlMDhjOGE2Y2IwMzNhYTZjZTg1MGU=
  jwt-token: OGRiOGY4NTk5MWJiMjhmNDVhYzAxMDdmMmExYjM0OWM=
  jobber-redis-host: cmVkaXM6Ly9qb2JiZXItcmVkaXMtY2FjaGUud3Q2eGNhLmNsdXN0ZXJjZmcuZXVjMS5jYWNoZS5hbWF6b25hd3MuY29tOjYzNzk=
  sender-email: YmVudG9uLnBmYW5uZXJzdGlsbEBldGhlcmVhbC5lbWFpbA==
  sender-email-password: bUZDdVYyRWFiSkp2MTk5Smhz
  jobber-mysql-db: bXlzcWw6Ly9qb2JiZXJhZG1pbjpqb2JiZXJhZG1pbjEyQGpvYmJlci1hdXRoLmNib2llMW4ya3RpYS5ldS1jZW50cmFsLTEucmRzLmFtYXpvbmF3cy5jb20vam9iYmVyX2F1dGg=
  jobber-postgres-host: am9iYmVyLWF1dGgtcG9zdGdyZXMuY2JvaWUxbjJrdGlhLmV1LWNlbnRyYWwtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  jobber-postgres-user: am9iYmVyYWRtaW4=
  jobber-postgres-password: am9iYmVyYWRtaW4xMg==
  cloud-name: ZHlhbXI5eW0z
  cloud-api-key: Mzg1MjY5MTkzOTgyMTQ3
  cloud-api-secret: LWg5aFU0M1FNeTY4QWNJYU15UDBVTEtiaWJJ
  mongo-database-url: bW9uZ29kYitzcnY6Ly9qb2JiZXJhZG1pbjpxYzRvQUU4dTlTTVJPUnA3QGpvYmJlci53YjdkcW1hLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  stripe-api-key: c2tfdGVzdF81MU9BWHM2RFRnbHZNZUpQcmxYMUxwOU13N2FYd2xCYkZKT0xRZGxrRnY1bVJLUGtRZEZyeHZZTjY4eFo1NHdCcjZWYlA0NGtoU001VXBQdGZhaXhsTWdjVzAwQ0laRXBtbjU=
  stripe-client-key: c2tfdGVzdF81MU9BWHM2RFRnbHZNZUpQcmxYMUxwOU13N2FYd2xCYkZKT0xRZGxrRnY1bVJLUGtRZEZyeHZZTjY4eFo1NHdCcjZWYlA0NGtoU001VXBQdGZhaXhsTWdjVzAwQ0laRXBtbjU=
  jobber-rabbitmq-user: am9iYmVy
  jobber-rabbitmq-password: am9iYmVycGFzcw==
  jobber-rabbitmq-endpoint: YW1xcDovL2pvYmJlcjpqb2JiZXJwYXNzQGpvYmJlci1xdWV1ZS5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=
  jobber-elasticsearch-url: aHR0cHM6Ly9lbGFzdGljOkNMV3NvMjNBVkZCYXh6ZERDNjltckdHcEBqb2JiZXJhcHAuZXMuZXUtY2VudHJhbC0xLmF3cy5jbG91ZC5lcy5pbw==
  jobber-elastic-apm-server-url: aHR0cHM6Ly8zNmQ4NmU0YWIwZWY0NjA3YTU4ODIxM2U1ZjdlMmRlMy5hcG0uZXUtY2VudHJhbC0xLmF3cy5jbG91ZC5lcy5pbzo0NDM=
  jobber-elastic-apm-secret-token: MkNQQ2V1RXRPeFU3OU9UQzNr
  jobber-elasticsearch-host: am9iYmVyYXBwLmVzLmV1LWNlbnRyYWwtMS5hd3MuY2xvdWQuZXMuaW8=
  jobber-elasticsearch-username: ZWxhc3RpYw==
  jobber-elasticsearch-password: Q0xXc28yM0FWRkJheHpkREM2OW1yR0dw
  jobber-elastic-cloud-id: am9iYmVyYXBwOlpYVXRZMlZ1ZEhKaGJDMHhMbUYzY3k1amJHOTFaQzVsY3k1cGJ6bzBORE1rT0dOa05EaG1NR0pqWWpGbE5ETXdOVGhoWm1JeFl6Y3lNR1ExTW1NM056VWtZamxtT1RnNFlqSTNNelpoTkRjME5Ua3lZamhrTmpBeU5HWmxOakUzWmpJPQ==
  # <elasticsearch-username>:<elasticsearch-password>
  jobber-elastic-cloud-auth: ZWxhc3RpYzpDTFdzbzIzQVZGQmF4emREQzY5bXJHR3A=
